#!/bin/bash

set -eu
set pipefail

DEADLINE="${XDG_STATE_HOME:-/home/vim-win32/.local/state}/vim-win32-deadline"

if [ -r "$DEADLINE" ]; then
  next="$(cat "$DEADLINE")"
  # convert to UTC epoch time from date
  next="$(date --utc +%s -d "$next")"
  TZ='' systemd-run --collect --on-calendar="@$next" \
    --timer-property=AccuracySec=1s --unit="vim-win32-fetch.service"
  rm -f "$DEADLINE"
fi
